#!python3
import pyautogui
import time

time.sleep(5)
pyautogui.keyDown('f1')
pyautogui.keyUp('f1')
pyautogui.keyDown('f12')
pyautogui.keyUp('f12')
time.sleep(1)
pyautogui.keyDown('right')
time.sleep(16)
pyautogui.keyUp('right')
pyautogui.keyDown('down')
time.sleep(2)
pyautogui.keyUp('down')
pyautogui.keyDown('right')
time.sleep(8)
pyautogui.keyUp('right')
pyautogui.keyDown('down')
time.sleep(5)
pyautogui.keyDown('left')
time.sleep(1)
pyautogui.keyUp('left')
pyautogui.keyUp('down')
pyautogui.keyDown('right')